# Spring Cloud Eureka 服务器应用名称
spring:
  application:
    name: spring-cloud-eureka-server

# Spring Cloud Eureka 服务器服务端口
server:
  port: 8761

# 管理端口安全失效
management:
  security:
    enabled: false

# Spring Cloud Eureka 服务器作为注册中心
# 通常情况下，不需要再注册到其他注册中心去
# 同时，它也不需要获取客户端信息
# 取消向注册中心注册
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    # 取消向注册中心获取注册信息（服务、实例信息）
    fetch-registry: false
    # 解决 Peer / 集群 连接问题
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka