# peer 1 完整配置
# 配置 服务器端口
# peer 1 端口 9090
server:
  port: 9090

# peer 2 主机：localhost , 端口 9091
peer2:
  server:
    host: localhost
    port: 9091

# Eureka 注册信息
eureka:
  client:
    serviceUrl:
      defaultZone: http://${peer2.server.host}:${peer2.server.port}/eureka