# Spring Cloud Eureka 客户端应用名称
spring:
  application:
    name: spring-cloud-eureka-client

# Spring Cloud Eureka 客户端端口
server:
  port: 8080

# 管理端口安全实效
management:
  security:
    enabled: false

## Spring Cloud Eureka 客户端 注册到 Eureka 服务器
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    status-page-url-path: /status     # 调整状态页面
    health-check-url-path: /health    # 调整健康检查页面