# 配置服务器应用名称
spring:
  application:
    name: spring-cloud-config-client
# 配置服务器端口
server:
  port: 8020
# 关闭管理端actuator 的安全
# /env /health 端口完全开放
management:
  security:
    enabled: false

## 用户的配置信息
nc:
  user:
    id: 1     # 用户 ID
    name: springcloud     # 用户名称
